import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

const root = process.cwd();
const model = await fs.readFile(path.join(root, "src/lib/plasterOffers.ts"), "utf8");
// Preserve R2's pure-model regression tests for historic offer comparisons, even though
// the buyer-facing P01 no longer asks visitors to fill the full estimate matrix.
const js = ts.transpileModule(model, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { estimateItems, initialOffers, exampleOffers, summarizeOffers } = await import(`data:text/javascript;charset=utf-8,${encodeURIComponent(js)}`);
const total = estimateItems.length;
assert.equal(total, 8);
const all = (machine, hand = machine) => Object.fromEntries(estimateItems.map((item) => [item.id, { machine, hand }]));
const yes = [true, true, true];
const no = [false, false, false];

let result = summarizeOffers(initialOffers(), no, "single");
assert.equal(result.status, "empty");
assert.equal(result.clarified, 0);
assert.equal(result.baselineMissing, 0);
assert.equal(result.compositionReady, false);
const partial = initialOffers();
partial.preparation.machine = "included";
result = summarizeOffers(partial, no, "single");
assert.equal(result.status, "incomplete");
assert.equal(result.clarified, 1);
assert.equal(result.unresolved.length, 7);
assert.equal(summarizeOffers(partial, yes, "compare").clarified, 0);
result = summarizeOffers(all("included", "unknown"), no, "single");
assert.equal(result.compositionReady, true);
assert.equal(result.status, "complete");
assert.equal(summarizeOffers(all("included", "unknown"), yes, "compare").status, "empty");
result = summarizeOffers(all("included"), no, "compare");
assert.equal(result.clarified, total);
assert.equal(result.status, "baseline");
assert.equal(result.compositionReady, false);
result = summarizeOffers(all("included"), yes, "compare");
assert.equal(result.status, "complete");
assert.equal(result.compositionReady, true);
result = summarizeOffers(all("separate"), yes, "compare");
assert.equal(result.status, "additions");
assert.equal(result.compositionReady, true);
assert.equal(result.different.length, 0);
assert.equal(result.separate.length, total);
result = summarizeOffers(all("included", "separate"), yes, "compare");
assert.equal(result.status, "additions");
assert.equal(result.compositionReady, true);
assert.equal(result.different.length, total);
assert.equal(result.separate.length, total);
assert.equal(summarizeOffers(all("separate", "unknown"), no, "single").status, "additions");
assert.equal(summarizeOffers(all("separate", "unknown"), no, "single").compositionReady, true);
const mixed = all("included");
mixed.preparation.hand = "unknown";
result = summarizeOffers(mixed, yes, "compare");
assert.equal(result.status, "incomplete");
assert.equal(result.clarified, 7);
result = summarizeOffers(exampleOffers(), yes, "compare");
assert.equal(result.status, "additions");
assert.equal(result.compositionReady, true);
assert.equal(result.separate.length, 2);
assert.equal(result.different.length, 1);
assert.equal(exampleOffers().delivery.hand, "separate");

const component = await fs.readFile(path.join(root, "src/components/PlasterProcessGuide.tsx"), "utf8");
for (const phrase of ["Что выбрать для ваших стен?", "от 550 ₽/м²", "Пять вопросов, чтобы понять смету", "Что делать дальше?", "Подробнее: как проходят работы", "У меня две сметы — как их сравнить?", "Обсудить расчёт в WhatsApp", "whatsappUrl(contactText)"]) assert.ok(component.includes(phrase), `R4.1 client UI missing: ${phrase}`);
for (const old of ["slice(0, visibleCount)", "setVisibleCount", "role=\"progressbar\"", "scopeLabels.map", "setOffers", "Начните с одной позиции"]) assert.ok(!component.includes(old), `R4.1 must not display old mandatory matrix: ${old}`);
const slug = "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka";
const html = await fs.readFile(path.join(root, "dist", slug, "index.html"), "utf8");
for (const phrase of ["data-prerendered", "Что выбрать для ваших стен?", "от 550 ₽/м²", "Пять вопросов, чтобы понять смету", "У меня две сметы — как их сравнить?", "Подробнее: как проходят работы", "Обсудить расчёт в WhatsApp", "FAQPage", "Article", "rel=\"canonical\""]) assert.ok(html.includes(phrase), `R4.1 no-JS missing: ${phrase}`);
assert.ok(!html.includes("Уточнено 0 из 8") && !html.includes("Карта нанесения и проверки смет штукатурки"), "No-JS old mandatory matrix removed");
assert.ok(html.includes(`https://conradipui-glitch.github.io/silalesa/${slug}/`));
const products = await fs.readFile(path.join(root, "src/data/products.ts"), "utf8");
const contact = products.match(/whatsapp:\s*"(\d+)"/);
assert.ok(contact);
assert.ok(html.includes(`https://wa.me/${contact[1]}?text=`));
const sitemap = await fs.readFile(path.join(root, "dist/sitemap.xml"), "utf8");
assert.ok(sitemap.includes(`${slug}/`));
console.log("R2/R4.1 PASS: historical model scenarios, simple buyer UI, no-JS answer and price, optional details, contact, SEO/sitemap");
