// AUTO-GENERATED by scripts/generate-route-manifest.mjs. Do not hand-edit.
// Only routing keys are in the initial JS; full SEO content loads on relevant routes.
export const seoSlugs: string[] = [
  "banya-kvadro-2x2-omsk",
  "banya-kvadro-3x2-omsk",
  "banya-kvadro-4x2-omsk",
  "karkasnaya-banya-omsk",
  "mobilnaya-banya-omsk",
  "polusuhaya-styazhka-omsk",
  "mehanizirovannaya-shtukaturka-omsk",
  "burenie-skvazhiny-omsk",
  "guides/bani/fundament-dlya-mobilnoy-bani",
  "guides/bani/kvadro-ili-karkasnaya",
  "guides/bani/chto-vhodit-v-tsenu",
  "guides/bani/kak-vybrat-razmer-2x2-3x2-4x2",
  "guides/bani/gotovaya-ili-stroit",
  "guides/bani/podgotovka-uchastka-dostavka-manipulyator",
  "guides/bani/chek-list-priemki-gotovoy-bani",
  "guides/uchastok/kogda-burit-skvazhinu",
  "guides/remont/shtukaturka-ili-styazhka-chto-snachala",
  "guides/remont/polusuhaya-ili-mokraya-styazhka",
  "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka",
  "guides/remont/gipsovaya-ili-tsementnaya-shtukaturka"
];
export const productLandingById: Record<string, string> = {
  "10407084": "banya-kvadro-4x2-omsk",
  "10413511": "karkasnaya-banya-omsk",
  "10645493": "banya-kvadro-2x2-omsk",
  "10645551": "banya-kvadro-3x2-omsk",
  "12656055": "mehanizirovannaya-shtukaturka-omsk",
  "12656157": "polusuhaya-styazhka-omsk",
  "12791309": "burenie-skvazhiny-omsk"
};
