// AUTO-GENERATED by scripts/generate-route-manifest.mjs. Do not hand-edit.
// Only routing and CTA summaries are in entry JS; full SEO guides load on landing routes.
export const seoSlugs: string[] = [
  "polusuhaya-styazhka-omsk",
  "mehanizirovannaya-shtukaturka-omsk",
  "burenie-skvazhiny-omsk",
  "guides/uchastok/kogda-burit-skvazhinu",
  "guides/remont/shtukaturka-ili-styazhka-chto-snachala",
  "guides/remont/polusuhaya-ili-mokraya-styazhka",
  "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka",
  "guides/remont/gipsovaya-ili-tsementnaya-shtukaturka",
  "guides/stroitelstvo/skolko-stoit-kladka-kirpicha-i-gazobetona",
  "guides/remont/demontazh-pered-remontom-smeta"
];
export const landingMetaBySlug: Record<string, { h1: string; kind: string }> = {
  "polusuhaya-styazhka-omsk": {
    "h1": "Полусухая стяжка пола в Омске",
    "kind": "service"
  },
  "mehanizirovannaya-shtukaturka-omsk": {
    "h1": "Механизированная штукатурка стен и потолков в Омске",
    "kind": "service"
  },
  "burenie-skvazhiny-omsk": {
    "h1": "Бурение скважин на воду в Омске",
    "kind": "service"
  },
  "guides/uchastok/kogda-burit-skvazhinu": {
    "h1": "Когда лучше бурить скважину: до стройки или в другое время года?",
    "kind": "guide"
  },
  "guides/remont/shtukaturka-ili-styazhka-chto-snachala": {
    "h1": "Штукатурка или стяжка: что делать сначала?",
    "kind": "guide"
  },
  "guides/remont/polusuhaya-ili-mokraya-styazhka": {
    "h1": "Полусухая или мокрая стяжка: в чём разница и что выбрать?",
    "kind": "guide"
  },
  "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka": {
    "h1": "Механизированная или ручная штукатурка: в чём разница и что выбрать?",
    "kind": "guide"
  },
  "guides/remont/gipsovaya-ili-tsementnaya-shtukaturka": {
    "h1": "Гипсовая или цементная штукатурка: что выбрать и где применять?",
    "kind": "guide"
  },
  "guides/stroitelstvo/skolko-stoit-kladka-kirpicha-i-gazobetona": {
    "h1": "Сколько стоит кладка кирпича и газобетона?",
    "kind": "guide"
  },
  "guides/remont/demontazh-pered-remontom-smeta": {
    "h1": "Демонтаж перед ремонтом: как подготовить расчёт?",
    "kind": "guide"
  }
};
export const landingByProductId: Record<string, { slug: string; kind: string; lead: string; priceLabel: string | null }> = {
  "12656055": {
    "slug": "mehanizirovannaya-shtukaturka-omsk",
    "kind": "service",
    "lead": "Выравниваем стены и потолки с помощью штукатурной станции. Подберём состав под основание и будущую отделку: пришлите площадь и фотографии поверхностей, чтобы обсудить расчёт.",
    "priceLabel": "от 550 ₽/м²"
  },
  "12656157": {
    "slug": "polusuhaya-styazhka-omsk",
    "kind": "service",
    "lead": "Делаем полусухую цементно-песчаную стяжку, чтобы подготовить ровное основание под выбранное покрытие. Сообщите площадь, этаж и покажите основание — обсудим состав работ и стоимость.",
    "priceLabel": "от 600 ₽/м²"
  },
  "12791309": {
    "slug": "burenie-skvazhiny-omsk",
    "kind": "service",
    "lead": "Поможем пройти путь от выбора места под скважину до бурения, обсадки и прокачки. Расскажите, где находится участок и как планируете использовать воду: обсудим работы, оснащение и расчёт.",
    "priceLabel": "от 2 500 ₽/пог. м"
  }
};
