// AUTO-GENERATED by scripts/generate-route-manifest.mjs. Do not hand-edit.
// Only routing and CTA summaries are in entry JS; full SEO guides load on landing routes.
export const seoSlugs: string[] = [
  "banya-kvadro-2x2-omsk",
  "banya-kvadro-3x2-omsk",
  "banya-kvadro-4x2-omsk",
  "karkasnaya-banya-omsk",
  "mobilnaya-banya-omsk",
  "polusuhaya-styazhka-omsk",
  "mehanizirovannaya-shtukaturka-omsk",
  "burenie-skvazhiny-omsk",
  "guides/bani/fundament-dlya-mobilnoy-bani",
  "guides/bani/kvadro-ili-karkasnaya",
  "guides/bani/chto-vhodit-v-tsenu",
  "guides/bani/kak-vybrat-razmer-2x2-3x2-4x2",
  "guides/bani/gotovaya-ili-stroit",
  "guides/bani/podgotovka-uchastka-dostavka-manipulyator",
  "guides/bani/chek-list-priemki-gotovoy-bani",
  "guides/uchastok/kogda-burit-skvazhinu",
  "guides/remont/shtukaturka-ili-styazhka-chto-snachala",
  "guides/remont/polusuhaya-ili-mokraya-styazhka",
  "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka",
  "guides/remont/gipsovaya-ili-tsementnaya-shtukaturka"
];
export const landingMetaBySlug: Record<string, { h1: string; kind: string }> = {
  "banya-kvadro-2x2-omsk": {
    "h1": "Баня Квадро 2×2 в Омске",
    "kind": "sauna"
  },
  "banya-kvadro-3x2-omsk": {
    "h1": "Баня Квадро 3×2 в Омске",
    "kind": "sauna"
  },
  "banya-kvadro-4x2-omsk": {
    "h1": "Баня Квадро 4×2 в Омске",
    "kind": "sauna"
  },
  "karkasnaya-banya-omsk": {
    "h1": "Каркасная баня 5,5×2,2 под ключ в Омске",
    "kind": "sauna"
  },
  "mobilnaya-banya-omsk": {
    "h1": "Готовые мобильные бани под ключ в Омске",
    "kind": "category"
  },
  "polusuhaya-styazhka-omsk": {
    "h1": "Полусухая стяжка пола в Омске",
    "kind": "service"
  },
  "mehanizirovannaya-shtukaturka-omsk": {
    "h1": "Механизированная штукатурка стен и потолков в Омске",
    "kind": "service"
  },
  "burenie-skvazhiny-omsk": {
    "h1": "Бурение скважин на воду в Омске",
    "kind": "service"
  },
  "guides/bani/fundament-dlya-mobilnoy-bani": {
    "h1": "Фундамент под мобильную баню: что подготовить до установки",
    "kind": "guide"
  },
  "guides/bani/kvadro-ili-karkasnaya": {
    "h1": "Квадро или каркасная баня: что выбрать",
    "kind": "guide"
  },
  "guides/bani/chto-vhodit-v-tsenu": {
    "h1": "Что входит в цену готовой бани Квадро",
    "kind": "guide"
  },
  "guides/bani/kak-vybrat-razmer-2x2-3x2-4x2": {
    "h1": "Как выбрать размер Квадро: 2×2, 3×2 или 4×2",
    "kind": "guide"
  },
  "guides/bani/gotovaya-ili-stroit": {
    "h1": "Готовая баня или строить на участке: как сравнить варианты",
    "kind": "guide"
  },
  "guides/bani/podgotovka-uchastka-dostavka-manipulyator": {
    "h1": "Как подготовить участок к доставке бани: подъезд, манипулятор и установка",
    "kind": "guide"
  },
  "guides/bani/chek-list-priemki-gotovoy-bani": {
    "h1": "Чек-лист приёмки готовой бани: что проверить при передаче",
    "kind": "guide"
  },
  "guides/uchastok/kogda-burit-skvazhinu": {
    "h1": "Когда лучше бурить скважину: до стройки или в другое время года?",
    "kind": "guide"
  },
  "guides/remont/shtukaturka-ili-styazhka-chto-snachala": {
    "h1": "Штукатурка или стяжка: что делать сначала?",
    "kind": "guide"
  },
  "guides/remont/polusuhaya-ili-mokraya-styazhka": {
    "h1": "Полусухая или мокрая стяжка: в чём разница и что выбрать?",
    "kind": "guide"
  },
  "guides/remont/mehanizirovannaya-ili-ruchnaya-shtukaturka": {
    "h1": "Механизированная или ручная штукатурка: в чём разница и что выбрать?",
    "kind": "guide"
  },
  "guides/remont/gipsovaya-ili-tsementnaya-shtukaturka": {
    "h1": "Гипсовая или цементная штукатурка: что выбрать и где применять?",
    "kind": "guide"
  }
};
export const landingByProductId: Record<string, { slug: string; kind: string; lead: string; priceLabel: string | null }> = {
  "10407084": {
    "slug": "banya-kvadro-4x2-omsk",
    "kind": "sauna",
    "lead": "Квадро 4×2 — две более просторные зоны: комната отдыха 200×171 см и парная 200×200 см. Стандартная цена — 365 000 ₽. На фото показаны дополнительные опции: боковой вход, увеличенное окно и стеклянная дверца печи; их нельзя считать включёнными в базовую цену.",
    "priceLabel": null
  },
  "10413511": {
    "slug": "karkasnaya-banya-omsk",
    "kind": "sauna",
    "lead": "Каркасная баня 5,5×2,2 — три отдельных помещения: комната отдыха, помывочная и парная. Панорамное окно расположено в комнате отдыха. Цена начинается от 630 000 ₽; оснащение, условия доставки и установки уточняются для этой модели отдельно от стандарта Квадро.",
    "priceLabel": null
  },
  "10645493": {
    "slug": "banya-kvadro-2x2-omsk",
    "kind": "sauna",
    "lead": "Квадро 2×2 — одна парная без комнаты отдыха. Внутри 200×177 см; цена стандартной модели — 230 000 ₽. Для стандартной Квадро доставка по Омску и установка на блоки включены, особенности участка и опции уточняем до заказа.",
    "priceLabel": null
  },
  "10645551": {
    "slug": "banya-kvadro-3x2-omsk",
    "kind": "sauna",
    "lead": "Квадро 3×2 — две зоны в компактном корпусе: комната отдыха длиной 90 см и парная длиной 180 см. Стандартная цена — 320 000 ₽; доставка по Омску и установка на блоки включены для стандартной Квадро.",
    "priceLabel": null
  },
  "12656055": {
    "slug": "mehanizirovannaya-shtukaturka-omsk",
    "kind": "service",
    "lead": "Выравниваем стены и потолки с помощью штукатурной станции. Подберём состав под основание и будущую отделку: пришлите площадь и фотографии поверхностей, чтобы обсудить расчёт.",
    "priceLabel": "от 550 ₽/м²"
  },
  "12656157": {
    "slug": "polusuhaya-styazhka-omsk",
    "kind": "service",
    "lead": "Делаем полусухую цементно-песчаную стяжку, чтобы подготовить ровное основание под выбранное покрытие. Сообщите площадь, этаж и покажите основание — обсудим состав работ и стоимость.",
    "priceLabel": "от 600 ₽/м²"
  },
  "12791309": {
    "slug": "burenie-skvazhiny-omsk",
    "kind": "service",
    "lead": "Поможем пройти путь от выбора места под скважину до бурения, обсадки и прокачки. Расскажите, где находится участок и как планируете использовать воду: обсудим работы, оснащение и расчёт.",
    "priceLabel": "от 2 500 ₽/пог. м"
  }
};
